openapi: 3.0.1
info:
  title: Notification_API
  description: API Definition of Notification_API
  version: 1.0.0
servers:
- url: http://localhost:8290/notification/send
paths:
  /:
    post:
      responses:
        default:
          description: Default response
