openapi: 3.0.1
info:
  title: DynamicMediationSequence
  description: API Definition of DynamicMediationSequence
  version: 1.0.0
servers:
- url: http://localhost:8290/dynamic_mediation_seq
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
