openapi: 3.0.1
info:
  title: SampleTest_API
  description: API Definition of SampleTest_API
  version: 1.0.0
servers:
- url: http://localhost:8290/sample_test
paths:
  /:
    get:
      responses:
        default:
          description: Default response
